config/routes.rb
Chatter::Application.routes.draw do

  resources :channels
  resources :messages
  resources :chats
  root :to => 'static#home'
  
  ##################### Omniauth ########################
  match '/auth/:provider/callback' => 'authentications#create'
  delete '/logout' => 'authentications#destroy'
  #######################################################
  
  match "/channels-user-active" => "channels#user_active"
  match "/channels-user-inactive" => "channels#user_inactive"

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  # associations
  belongs_to :school
  has_many :chats
  has_many :users, :through => :chats
  
  # validations
  validates :name, :uniqueness => true
  
    
  def check_active_users
    self.users.each do |u|
      c = Chat.find_by_user_id_and_channel_id(u.id, self.id)
      if (Time.now - c.updated_at) > 20
        self.users.delete(u)
      end
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  # GET /channels
  # GET /channels.xml
  def index
    @channels = Channel.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.xml
  def show
    @channel = Channel.find(params[:id])
    c = Chat.find_by_user_id_and_channel_id(current_user.id, @channel.id)
    if !c
      Chat.create(:user_id => current_user.id, :channel_id => @channel.id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.xml
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.xml
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to(@channel, :notice => 'Channel was successfully created.') }
        format.xml  { render :xml => @channel, :status => :created, :location => @channel }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @channel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.xml
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to(@channel, :notice => 'Channel was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @channel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.xml
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to(channels_url) }
      format.xml  { head :ok }
    end
  end
  
  def user_inactive
    channel_name = params[:channel_name]
    puts "inactive!!!"
    puts channel_name
    c = Chat.find_by_user_id_and_channel_id(current_user.id, Channel.find_by_name(channel_name).id);
    puts c
    if c
      c.delete
    end
    
    render :json => { }
  end
  
  def user_active
    channel_id = params[:channel_id]
    c = Chat.find_by_user_id_and_channel_id(current_user.id, channel_id)
    if c
      c.touch
    else
      # Chat.create(:user_id => current_user.id, :channel_id => channel_id)
    end
    channel = Channel.find(channel_id)
    channel.check_active_users
    
    render :json => { :users => channel.users }
  end

end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
  <div id="<%= channel.name %>" class="chat-channel">
    <div class="chat-sidebar">
      <div class="chat-info">
        <h2><%= channel.name %></h2>
        <span class="school"><%= channel.school.name %></span>
        <p class="description"><%= channel.description %></p> 
      </div>
      <div class="chat-members">
        <span class="members-header">Who's here?</span>
        <ul class="member-list">
        </ul>
      </div>
    </div>
    <div class="chat-window">
      <ul class="chat" id="chat-<%= channel.id %>">
    
      </ul>
      <div class="chat-input">
      <%= form_for Message.new, :html => { :id => 'new_message_' + channel.id.to_s },  :remote => true do |f| %>
        <%= f.hidden_field :chan_id, :id => 'message_channel_id_' + channel.id.to_s, :value => channel.id %>
        <%= f.text_field :content, :id => 'message_content_' + channel.id.to_s, :class => 'message_content', :placeholder => "Send a Message", :autocomplete => "off" %>
        <!--<%= f.submit "Send" %>-->
      <% end %>
      </div>
    </div>
  </div>

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :school_id %><br />
    <%= f.text_field :school_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<script>
$(function() {
  <% current_user.channels.each do |channel| %>
    setInterval(function() { $.ajax({
      type: 'POST',
      url: '/channels-user-active',
      dataType: "json",
      data: "channel_id=<%= channel.id %>",
      success: function(response) { }
    });}, 6000);
  <% end %>
});


<% current_user.channels.each do |channel| %>
window.onload=function() { $.ajax({
      type: 'POST',
      url: '/channels-user-active',
      dataType: "json",
      data: "channel_id=<%= channel.id %>",
      success: function(response) { }
    });};
  <% end %>




</script>
<div class="container">
<div id="channels-index">
  <div id="welcome-msg">
  <h2>Welcome to discourse!</h2>
  <img src="/images/tartanhacks.png" style="float:left;margin:30px" />
  <p>Join a channel below, or create a 
  <%= link_to 'new channel', new_channel_path %> 
  to start chatting.<br /> You are currently browsing the
  Carnegie Mellon University network. </p>
  </div>
  <table id="channels-list">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <!--<th></th>
      <th></th>-->
    </tr>
  <% @channels.each do |channel| %>
    <tr class="<%= cycle('even', 'odd') %>">
      <td><%= channel.name %></td>
      <td><%= channel.description %></td>
      <td><%= link_to 'Join', "/chats/"+channel.id.to_s, :method => :put %></td>
      <!--<td><%= link_to 'Edit', edit_channel_path(channel) %></td>-->
      <!--<td><%= link_to 'Destroy', channel, :confirm => 'Are you sure?', :method => :delete %></td>-->
    </tr>
  <% end %>
  </table>
</div>
</div>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<script>
function sortName(a,b){  
  if (a.user.name == b.user.name){
   return 0;
  }
  return a.user.name > b.user.name ? 1 : -1;  
}; 

//Updates the current users in channel once page loads
/*$(function (){
var initialChannel = "<%= @channel.name %>";
<% current_user.channels.each do |channel| %>
  function() { $.ajax({
        type: 'POST',
        url: '/channels-user-active',
        dataType: "json",
        data: "channel_id=<%= channel.id %>",
        success: function(response) {
          $("#<%= channel.name %> .member-list").empty();
          var users = response.users.sort(sortName);
          $.each(response.users, function(index, value) {
            $("#<%= channel.name %> .member-list").append(
              '<li><img src="http://graph.facebook.com/'
              +value.user.uid+
              '/picture" />'
              +value.user.name+'</li>'
            );
          });
        }
      });};
  <% end %>
  $(".chat-channel").hide();
  $("#" + initialChannel).show();
  $("#tab-" + initialChannel).addClass('active');
});
*/

$(function() {
  var initialChannel = "<%= @channel.name %>";
  var faye = new Faye.Client('http://fayeserv.herokuapp.com/faye');
  <% current_user.channels.each do |channel| %>
    faye.subscribe("/channels/<%= channel.id %>", function(data) {
      eval(data);
    });
    setInterval(function() { $.ajax({
      type: 'POST',
      url: '/channels-user-active',
      dataType: "json",
      data: "channel_id=<%= channel.id %>",
      success: function(response) {
        $("#<%= channel.name %> .member-list").empty();
        var users = response.users.sort(sortName);
        $.each(response.users, function(index, value) {
          $("#<%= channel.name %> .member-list").append(
            '<li><img src="http://graph.facebook.com/'
            +value.user.uid+
            '/picture" />'
            +value.user.name+'</li>'
          );
        });
      }
    });}, 6000);
  <% end %>
  
  
  $(".chat-channel").hide();
  $("#" + initialChannel).show();
  $("#tab-" + initialChannel).addClass('active');
});

$(".close-tab").live('click', function(event) {
  event.stopPropagation();
});

$(".tab").live('click', function(event) {
  $(".tab").removeClass("active");
  $(this).removeClass('alert').addClass("active");
  event.preventDefault();
  $(".chat-channel").fadeOut(250);
  $("#" + $(this).attr('channel')).fadeIn(250);
});
</script>
<div class="container">
<%= render :partial => "channel", :collection => current_user.channels %>
</div>